language: php

matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: COMPOSER_FLAGS=""
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: COMPOSER_FLAGS=""
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: COMPOSER_FLAGS=""
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.3
      env: COMPOSER_FLAGS=""
    - php: 8.0.0-dev
      env: COMPOSER_FLAGS="--prefer-lowest --ignore-platform-reqs"
    - php: 8.0.0-dev
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: nightly
      env: COMPOSER_FLAGS="--prefer-lowest --ignore-platform-reqs"
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: 7.3
      env: MULTITEST='on'
  allow_failures:
    - php: 8.0.0-dev
      env: COMPOSER_FLAGS="--prefer-lowest --ignore-platform-reqs"
    - php: 8.0.0-dev
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: nightly
      env: COMPOSER_FLAGS="--prefer-lowest --ignore-platform-reqs"
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - if [ "$MULTITEST" != "on" ]; then phpunit --coverage-text --coverage-clover=coverage.clover; fi;
  - if [ "$MULTITEST" = "on" ]; then vendor/bin/multi-tester; fi;

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
