language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 8.0
  - nightly

matrix:
  include:
    - php: 7.3
      env: MULTITEST='on'
  allow_failures:
    - php: 8.0
    - php: nightly
  fast_finish: true

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - if [ "$MULTITEST" != "on" ]; then phpunit --coverage-text --coverage-clover=coverage.clover; fi;
  - if [ "$MULTITEST" = "on" ]; then vendor/bin/multi-tester; fi;

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
